services:
  app:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: helloworld 
      MYSQL_DATABASE: app_db
      MYSQL_USER: hello
      MYSQL_PASSWORD: helloworld1
    ports:
      - "6100:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: "512M"
    restart: always
    ports:
      - 8100:80


volumes:
  dbdata:

    