"""Initial migration

Revision ID: 03f6c760e58e
Revises: 
Create Date: 2025-05-11 16:58:40.819995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03f6c760e58e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('UserID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=False),
    sa.Column('LastName', sa.String(length=100), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('UserType', sa.Enum('student', 'lecturer', 'admin', name='usertype'), nullable=False),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_table('Admin',
    sa.Column('AdminID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AdminID'], ['User.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('AdminID')
    )
    op.create_table('Lecturer',
    sa.Column('LecturerID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LecturerID'], ['User.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('LecturerID')
    )
    op.create_table('Student',
    sa.Column('StudentID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['StudentID'], ['User.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('StudentID')
    )
    op.create_table('Course',
    sa.Column('CourseCode', sa.String(length=8), nullable=False),
    sa.Column('CourseName', sa.String(length=255), nullable=False),
    sa.Column('LecturerID', sa.Integer(), nullable=False),
    sa.Column('AdminID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AdminID'], ['Admin.AdminID'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['LecturerID'], ['Lecturer.LecturerID'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('CourseCode')
    )
    op.create_table('Assignment',
    sa.Column('AssignmentID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CourseCode', sa.String(length=8), nullable=False),
    sa.Column('Content', sa.Text(), nullable=True),
    sa.Column('DueDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['CourseCode'], ['Course.CourseCode'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('AssignmentID')
    )
    op.create_table('CalendarEvents',
    sa.Column('EventID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CourseCode', sa.String(length=8), nullable=False),
    sa.Column('EventName', sa.String(length=255), nullable=False),
    sa.Column('EventDate', sa.DateTime(), nullable=False),
    sa.Column('CreatedBy', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CourseCode'], ['Course.CourseCode'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['CreatedBy'], ['User.UserID'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('EventID')
    )
    op.create_table('DiscussionForum',
    sa.Column('ForumID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CourseCode', sa.String(length=8), nullable=False),
    sa.Column('ForumName', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['CourseCode'], ['Course.CourseCode'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ForumID')
    )
    op.create_table('Enrol',
    sa.Column('CourseCode', sa.String(length=8), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CourseCode'], ['Course.CourseCode'], ),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ),
    sa.PrimaryKeyConstraint('CourseCode', 'UserID')
    )
    op.create_table('Section',
    sa.Column('SectionID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CourseCode', sa.String(length=8), nullable=False),
    sa.Column('SectionTitle', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['CourseCode'], ['Course.CourseCode'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SectionID')
    )
    op.create_table('DiscussionThread',
    sa.Column('ThreadID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ForumID', sa.Integer(), nullable=False),
    sa.Column('ThreadTitle', sa.String(length=255), nullable=False),
    sa.Column('Content', sa.Text(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['CreatedBy'], ['User.UserID'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ForumID'], ['DiscussionForum.ForumID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ThreadID')
    )
    op.create_table('SectionItem',
    sa.Column('SectionItemID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SectionID', sa.Integer(), nullable=False),
    sa.Column('ItemTitle', sa.String(length=255), nullable=False),
    sa.Column('Link', sa.String(length=2083), nullable=True),
    sa.Column('Filename', sa.String(length=255), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['SectionID'], ['Section.SectionID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SectionItemID')
    )
    op.create_table('Submission',
    sa.Column('SubmissionID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('StudentID', sa.Integer(), nullable=False),
    sa.Column('AssignmentID', sa.Integer(), nullable=False),
    sa.Column('SubmissionContent', sa.Text(), nullable=True),
    sa.Column('UploadDate', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['AssignmentID'], ['Assignment.AssignmentID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['StudentID'], ['Student.StudentID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SubmissionID'),
    sa.UniqueConstraint('StudentID', 'AssignmentID', name='uq_student_assignment')
    )
    op.create_table('Grade',
    sa.Column('SubmissionID', sa.Integer(), nullable=False),
    sa.Column('LecturerID', sa.Integer(), nullable=False),
    sa.Column('Score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['LecturerID'], ['Lecturer.LecturerID'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['SubmissionID'], ['Submission.SubmissionID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SubmissionID')
    )
    op.create_table('Reply',
    sa.Column('ReplyID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ThreadID', sa.Integer(), nullable=False),
    sa.Column('ParentReplyID', sa.Integer(), nullable=True),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('CreatedBy', sa.Integer(), nullable=False),
    sa.Column('ReplyDate', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['CreatedBy'], ['User.UserID'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ParentReplyID'], ['Reply.ReplyID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ThreadID'], ['DiscussionThread.ThreadID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ReplyID')
    )
    op.create_table('ThreadVote',
    sa.Column('ThreadID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Vote', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ThreadID'], ['DiscussionThread.ThreadID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ThreadID', 'UserID')
    )
    op.create_table('ReplyVote',
    sa.Column('ReplyID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Vote', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ReplyID'], ['Reply.ReplyID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ReplyID', 'UserID')
    )
    op.drop_table('assignment')
    op.drop_table('course')
    op.drop_table('admin')
    op.drop_table('sectionitem')
    op.drop_table('discussionforum')
    op.drop_table('grade')
    op.drop_table('student')
    op.drop_table('section')
    op.drop_table('lecturer')
    op.drop_index('StudentID', table_name='submission')
    op.drop_table('submission')
    op.drop_table('discussionthread')
    op.drop_table('enrol')
    op.drop_table('calendarevents')
    op.drop_table('threadvote')
    op.drop_table('user')
    op.drop_table('reply')
    op.drop_table('replyvote')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replyvote',
    sa.Column('ReplyID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Vote', mysql.TINYINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ReplyID'], ['reply.ReplyID'], name='replyvote_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], name='replyvote_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ReplyID', 'UserID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reply',
    sa.Column('ReplyID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ThreadID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ParentReplyID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Content', mysql.TEXT(), nullable=False),
    sa.Column('CreatedBy', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ReplyDate', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['CreatedBy'], ['user.UserID'], name='reply_ibfk_3', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ParentReplyID'], ['reply.ReplyID'], name='reply_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ThreadID'], ['discussionthread.ThreadID'], name='reply_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ReplyID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('UserID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('FirstName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('LastName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('UserType', mysql.ENUM('student', 'lecturer', 'admin'), nullable=False),
    sa.PrimaryKeyConstraint('UserID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('threadvote',
    sa.Column('ThreadID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Vote', mysql.TINYINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ThreadID'], ['discussionthread.ThreadID'], name='threadvote_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], name='threadvote_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ThreadID', 'UserID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('calendarevents',
    sa.Column('EventID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CourseCode', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('EventName', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('EventDate', mysql.DATETIME(), nullable=False),
    sa.Column('CreatedBy', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['CourseCode'], ['course.CourseCode'], name='calendarevents_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['CreatedBy'], ['user.UserID'], name='calendarevents_ibfk_2', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('EventID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('enrol',
    sa.Column('CourseCode', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['CourseCode'], ['course.CourseCode'], name='enrol_ibfk_2'),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], name='enrol_ibfk_1'),
    sa.PrimaryKeyConstraint('CourseCode', 'UserID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('discussionthread',
    sa.Column('ThreadID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ForumID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ThreadTitle', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Content', mysql.TEXT(), nullable=True),
    sa.Column('CreatedBy', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('UpdatedAt', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['CreatedBy'], ['user.UserID'], name='discussionthread_ibfk_2', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ForumID'], ['discussionforum.ForumID'], name='discussionthread_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ThreadID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('submission',
    sa.Column('SubmissionID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('StudentID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('AssignmentID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SubmissionContent', mysql.TEXT(), nullable=True),
    sa.Column('UploadDate', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['AssignmentID'], ['assignment.AssignmentID'], name='submission_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['StudentID'], ['student.StudentID'], name='submission_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SubmissionID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('StudentID', 'submission', ['StudentID', 'AssignmentID'], unique=True)
    op.create_table('lecturer',
    sa.Column('LecturerID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['LecturerID'], ['user.UserID'], name='lecturer_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('LecturerID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('section',
    sa.Column('SectionID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CourseCode', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('SectionTitle', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['CourseCode'], ['course.CourseCode'], name='section_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SectionID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student',
    sa.Column('StudentID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['StudentID'], ['user.UserID'], name='student_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('StudentID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('grade',
    sa.Column('SubmissionID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('LecturerID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Score', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['LecturerID'], ['lecturer.LecturerID'], name='grade_ibfk_2', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['SubmissionID'], ['submission.SubmissionID'], name='grade_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SubmissionID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('discussionforum',
    sa.Column('ForumID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CourseCode', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('ForumName', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['CourseCode'], ['course.CourseCode'], name='discussionforum_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ForumID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sectionitem',
    sa.Column('SectionItemID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('SectionID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ItemTitle', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Link', mysql.VARCHAR(length=2083), nullable=True),
    sa.Column('Filename', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Description', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['SectionID'], ['section.SectionID'], name='sectionitem_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SectionItemID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('admin',
    sa.Column('AdminID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['AdminID'], ['user.UserID'], name='admin_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('AdminID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('course',
    sa.Column('CourseCode', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('CourseName', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('LecturerID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('AdminID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['AdminID'], ['admin.AdminID'], name='course_ibfk_1', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('CourseCode'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('assignment',
    sa.Column('AssignmentID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CourseCode', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('Content', mysql.TEXT(), nullable=True),
    sa.Column('DueDate', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['CourseCode'], ['course.CourseCode'], name='assignment_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('AssignmentID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('ReplyVote')
    op.drop_table('ThreadVote')
    op.drop_table('Reply')
    op.drop_table('Grade')
    op.drop_table('Submission')
    op.drop_table('SectionItem')
    op.drop_table('DiscussionThread')
    op.drop_table('Section')
    op.drop_table('Enrol')
    op.drop_table('DiscussionForum')
    op.drop_table('CalendarEvents')
    op.drop_table('Assignment')
    op.drop_table('Course')
    op.drop_table('Student')
    op.drop_table('Lecturer')
    op.drop_table('Admin')
    op.drop_table('User')
    # ### end Alembic commands ###
